import { LegalPage } from "@/components/legal-page";

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated="May 3, 2026"
      intro={
        <p>
          These terms govern your use of Reality Compiler (the "Service"). By
          creating an account or using the Service, you agree to them. If you
          do not agree, do not use the Service.
        </p>
      }
      sections={[
        {
          id: "eligibility",
          title: "1. Eligibility",
          body: (
            <>
              <p>
                You must be at least 18 years old to use the Service. By
                creating an account you confirm that you are of legal age in
                your jurisdiction to enter into binding contracts.
              </p>
            </>
          ),
        },
        {
          id: "accounts",
          title: "2. Accounts",
          body: (
            <p>
              You are responsible for the activity that happens under your
              account and for keeping your sign-in credentials secret. We use
              Clerk for authentication and may suspend accounts that show
              signs of abuse, fraud, or automated scraping.
            </p>
          ),
        },
        {
          id: "service",
          title: "3. The Service",
          body: (
            <>
              <p>
                Reality Compiler turns plain-English prompts into structured
                product specs, concept renders, bills of materials, and
                supplier quotes. Output is generated by AI models and is
                provided "as is" — it is a starting point, not a substitute
                for professional engineering review.
              </p>
              <p>
                We do not guarantee that any quoted price, lead time, or
                material is achievable in production. Always verify with the
                contract manufacturer before placing a binding order.
              </p>
            </>
          ),
        },
        {
          id: "user-content",
          title: "4. Your content",
          body: (
            <p>
              You retain all rights to the prompts you submit and the designs
              the Service generates from them. By using the Service you grant
              us a worldwide, royalty-free licence to host, store, and
              process that content for the purpose of operating the Service.
              Listings published to the marketplace are visible to other
              users until you unpublish them.
            </p>
          ),
        },
        {
          id: "acceptable-use",
          title: "5. Acceptable use",
          body: (
            <p>
              You agree to follow our{" "}
              <a href="/acceptable-use" className="text-primary underline">
                Acceptable Use Policy
              </a>
              . Violations may lead to content removal, account suspension,
              or termination.
            </p>
          ),
        },
        {
          id: "payments",
          title: "6. Orders, fees &amp; designer payouts",
          body: (
            <>
              <p>
                Orders placed through the Service are fulfilled by independent
                contract manufacturers. We facilitate the order, take a
                platform fee, and remit any designer payout to the creator of
                the original marketplace listing.
              </p>
              <p>
                <strong>Revenue split.</strong> Unless a separate written
                agreement says otherwise, marketplace orders are split{" "}
                <strong>70 % to the designer / 30 % to Reality Compiler</strong>{" "}
                of the order subtotal (price × quantity, net of refunds,
                chargebacks, taxes, and manufacturing cost). The 30 % covers
                payment processing, hosting, AI inference, supplier
                coordination, and platform support.
              </p>
              <p>
                <strong>Payout conditions.</strong> Designer payouts accrue on
                the order's <em>delivered</em> status and become payable{" "}
                <strong>14 days after delivery</strong> (the dispute window).
                Payouts of $50 or more are issued automatically; smaller
                balances roll over until the threshold is reached. We may
                withhold a payout pending investigation of suspected fraud,
                IP infringement, AUP violations, or chargebacks.
              </p>
              <p>
                <strong>Refunds.</strong> Buyers may request a refund within
                14 days of delivery for items that materially differ from the
                listing, arrive damaged, or are not delivered. Approved
                refunds are reversed against the original order, including
                the designer payout for that order. We do not refund custom
                or "made-to-order" items that match the spec accepted by the
                buyer at checkout.
              </p>
              <p>
                <strong>Intellectual property &amp; licence.</strong> You
                retain ownership of designs you create. By publishing a
                marketplace listing you grant Reality Compiler a worldwide,
                non-exclusive, royalty-free licence to host, display,
                transmit, and reproduce the listing's images, text, and BOM
                for the purposes of operating the marketplace, fulfilling
                orders, and promoting the Service. Buyers receive the
                physical good only — they do not receive a licence to the
                underlying design files or to manufacture additional units
                without your separate consent.
              </p>
            </>
          ),
        },
        {
          id: "termination",
          title: "7. Termination",
          body: (
            <p>
              You may delete your account at any time from{" "}
              <a href="/my-profile" className="text-primary underline">
                My Profile
              </a>
              . Deletion soft-deletes your sessions and listings, anonymises
              past orders, and triggers a 30-day purge of your stored
              objects. We may suspend or terminate accounts that violate
              these terms.
            </p>
          ),
        },
        {
          id: "disclaimer",
          title: "8. Disclaimers &amp; liability",
          body: (
            <p>
              The Service is provided "as is" and "as available" without
              warranties of any kind, express or implied. To the maximum
              extent permitted by law, we are not liable for any indirect,
              incidental, special, consequential, or punitive damages
              arising from your use of the Service.
            </p>
          ),
        },
        {
          id: "changes",
          title: "9. Changes",
          body: (
            <p>
              We may update these terms from time to time. Material changes
              will be announced in the product. Continued use after a change
              means you accept the new terms.
            </p>
          ),
        },
        {
          id: "contact",
          title: "10. Contact",
          body: (
            <p>
              Questions? Reach us at{" "}
              <a href="/contact" className="text-primary underline">
                the contact page
              </a>
              .
            </p>
          ),
        },
      ]}
    />
  );
}
