import { db, suppliersTable } from "@workspace/db";
import { sql } from "@workspace/db";
import { logger } from "./logger";

const SUPPLIERS = [
  {
    slug: "meridian-cnc",
    name: "Meridian CNC Works",
    tagline: "Precision 3-5 axis CNC for short-run aluminum and steel.",
    description:
      "A 40-machine CNC shop in Shenzhen specializing in tight-tolerance aluminum, brass, and stainless steel parts for consumer hardware. Strong at one-off prototyping through 5,000-unit pilot runs.",
    location: "Shenzhen, China",
    country: "China",
    capabilities: ["CNC machining", "Anodizing", "Bead blasting", "Tumbling"],
    materials: [
      "6061 Aluminum",
      "7075 Aluminum",
      "304 Stainless Steel",
      "316 Stainless Steel",
      "Brass",
      "Anodized Aluminum",
    ],
    certifications: ["ISO 9001", "ISO 14001"],
    leadTimeMinDays: 14,
    leadTimeMaxDays: 28,
    pricingMultiplier: "1.10",
    setupFee: "350.00",
    rating: "4.70",
    capacityLevel: "high",
  },
  {
    slug: "atlas-precision",
    name: "Atlas Precision Machining",
    tagline: "US-based CNC + finishing for regulated and aerospace work.",
    description:
      "Indiana-based machine shop with AS9100 certification. Higher unit cost in exchange for short freight, NIST-traceable inspection, and ITAR-friendly production.",
    location: "Indianapolis, USA",
    country: "USA",
    capabilities: ["CNC machining", "Surface grinding", "Inspection (CMM)"],
    materials: [
      "6061 Aluminum",
      "Titanium",
      "304 Stainless Steel",
      "Tool Steel",
      "Brass",
    ],
    certifications: ["AS9100", "ISO 9001", "ITAR"],
    leadTimeMinDays: 10,
    leadTimeMaxDays: 21,
    pricingMultiplier: "1.85",
    setupFee: "650.00",
    rating: "4.85",
    capacityLevel: "medium",
  },
  {
    slug: "kelvin-metal-am",
    name: "Kelvin Metal AM",
    tagline: "DMLS / SLM metal 3D printing for complex geometry.",
    description:
      "Specialists in direct metal laser sintering. Best for low-volume parts where geometry would otherwise require 5-axis CNC + EDM.",
    location: "Eindhoven, Netherlands",
    country: "Netherlands",
    capabilities: [
      "Metal 3D printing",
      "DMLS",
      "SLM",
      "Heat treatment",
      "CNC finishing",
    ],
    materials: [
      "Stainless Steel",
      "316L Stainless Steel",
      "Titanium",
      "Inconel",
      "Aluminum",
    ],
    certifications: ["ISO 9001", "ISO 13485"],
    leadTimeMinDays: 12,
    leadTimeMaxDays: 25,
    pricingMultiplier: "2.40",
    setupFee: "300.00",
    rating: "4.60",
    capacityLevel: "low",
  },
  {
    slug: "stratos-fdm",
    name: "Stratos FDM Lab",
    tagline: "Industrial FDM in PA, PETG, and carbon-filled nylon.",
    description:
      "Thirty large-format FDM printers running 24/7. Ideal for fixtures, enclosures, and pre-tooling validation parts.",
    location: "Berlin, Germany",
    country: "Germany",
    capabilities: ["3D printing", "FDM", "Vapor smoothing", "Hand finishing"],
    materials: [
      "PETG",
      "PLA",
      "ABS",
      "Carbon-filled Nylon",
      "PA12",
      "Recycled Polypropylene",
    ],
    certifications: ["ISO 9001"],
    leadTimeMinDays: 5,
    leadTimeMaxDays: 12,
    pricingMultiplier: "0.90",
    setupFee: "120.00",
    rating: "4.40",
    capacityLevel: "high",
  },
  {
    slug: "lumen-laser",
    name: "Lumen Laser & Sheet",
    tagline: "Fiber laser cutting + bending for sheet-metal enclosures.",
    description:
      "Sheet-metal specialist with 6kW fiber lasers and a 220-ton brake press. Strong on enclosures, mounts, and laser-engraved branding.",
    location: "Toronto, Canada",
    country: "Canada",
    capabilities: [
      "Laser cutting",
      "Sheet metal forming",
      "Press brake bending",
      "Powder coating",
      "Laser engraving",
    ],
    materials: [
      "Cold-rolled Steel",
      "Stainless Steel",
      "304 Stainless Steel",
      "Anodized Aluminum",
      "6061 Aluminum",
      "Brass",
    ],
    certifications: ["ISO 9001"],
    leadTimeMinDays: 7,
    leadTimeMaxDays: 18,
    pricingMultiplier: "1.05",
    setupFee: "275.00",
    rating: "4.55",
    capacityLevel: "medium",
  },
  {
    slug: "moldwerks-injection",
    name: "Moldwerks Injection",
    tagline: "Aluminum-tooled injection molding from 1,000 to 100,000 shots.",
    description:
      "Bridge-tooling injection molder. Aluminum molds in 3 weeks, MUD-base inserts for fast iteration. Pair with their in-house DfM review.",
    location: "Dongguan, China",
    country: "China",
    capabilities: [
      "Injection molding",
      "Tooling (aluminum)",
      "Insert molding",
      "Pad printing",
    ],
    materials: [
      "ABS",
      "Polycarbonate",
      "PA66",
      "TPU",
      "Recycled Polypropylene",
      "Food-grade Silicone",
    ],
    certifications: ["ISO 9001", "FDA-compatible cleanroom"],
    leadTimeMinDays: 25,
    leadTimeMaxDays: 50,
    pricingMultiplier: "0.65",
    setupFee: "2800.00",
    rating: "4.50",
    capacityLevel: "high",
  },
  {
    slug: "silicone-overmold-co",
    name: "Cascadia Silicone Co.",
    tagline: "Liquid silicone rubber overmolding & gaskets.",
    description:
      "LSR overmolding house focused on consumer wearables and medical devices. Two-shot capability for rigid + soft assemblies.",
    location: "Portland, USA",
    country: "USA",
    capabilities: [
      "Silicone overmolding",
      "LSR molding",
      "Two-shot molding",
      "Hand assembly",
    ],
    materials: [
      "Food-grade Silicone",
      "Medical-grade Silicone",
      "TPU",
      "Polycarbonate",
    ],
    certifications: ["ISO 13485", "FDA Class II"],
    leadTimeMinDays: 20,
    leadTimeMaxDays: 40,
    pricingMultiplier: "1.40",
    setupFee: "1800.00",
    rating: "4.65",
    capacityLevel: "medium",
  },
  {
    slug: "circuit-foundry",
    name: "Circuit Foundry",
    tagline: "Quick-turn PCB fabrication and SMT assembly.",
    description:
      "Up to 8-layer PCBs, 0201 SMT placement, full BGA support. Component sourcing handled in-house with a 50,000-part bonded inventory.",
    location: "Hsinchu, Taiwan",
    country: "Taiwan",
    capabilities: [
      "PCB fabrication",
      "PCB assembly",
      "SMT",
      "Through-hole",
      "Functional test",
    ],
    materials: [
      "FR4",
      "FR4 PCB",
      "Aluminum-backed PCB",
      "Flex PCB",
      "PMMA + LED PCB",
    ],
    certifications: ["IPC-A-610 Class 2/3", "ISO 9001", "RoHS"],
    leadTimeMinDays: 9,
    leadTimeMaxDays: 22,
    pricingMultiplier: "1.00",
    setupFee: "450.00",
    rating: "4.75",
    capacityLevel: "high",
  },
  {
    slug: "hempstead-textile",
    name: "Hempstead Textile Mill",
    tagline: "Cut-and-sew for soft goods, bags, and wearables.",
    description:
      "Vertically-integrated mill — fabric weaving, cutting, sewing, and finishing under one roof. Strong with technical fabrics and waxed canvas.",
    location: "Manchester, UK",
    country: "UK",
    capabilities: [
      "Cut and sew",
      "Embroidery",
      "Webbing assembly",
      "Heat-set bonding",
    ],
    materials: [
      "Organic Cotton",
      "Waxed Canvas",
      "Recycled Polyester",
      "Cordura",
      "TPU",
    ],
    certifications: ["GOTS", "OEKO-TEX 100"],
    leadTimeMinDays: 18,
    leadTimeMaxDays: 35,
    pricingMultiplier: "1.15",
    setupFee: "400.00",
    rating: "4.30",
    capacityLevel: "medium",
  },
  {
    slug: "maple-woodshop",
    name: "Maple Hill Woodshop",
    tagline: "FSC-certified hardwood machining and finishing.",
    description:
      "Family-owned shop running CNC routers and hand-finishing. Specializes in walnut, white oak, and bamboo for kitchenware and small furniture.",
    location: "Vermont, USA",
    country: "USA",
    capabilities: ["CNC routing", "Wood machining", "Hand finishing", "Oiling"],
    materials: ["Walnut", "White Oak", "Bamboo", "Maple", "Cork"],
    certifications: ["FSC"],
    leadTimeMinDays: 14,
    leadTimeMaxDays: 30,
    pricingMultiplier: "1.20",
    setupFee: "200.00",
    rating: "4.80",
    capacityLevel: "low",
  },
  {
    slug: "ironforge-casting",
    name: "Ironforge Die Casting",
    tagline: "Zinc and aluminum die casting for weighted bases.",
    description:
      "High-pressure die casting for parts that need mass — weighted lamp bases, knobs, mounts. In-house tumbling and powder coating.",
    location: "Pune, India",
    country: "India",
    capabilities: [
      "Die casting",
      "Zinc casting",
      "Aluminum casting",
      "Powder coating",
      "Tumbling",
    ],
    materials: ["Cast Zinc", "Cast Zinc + Silicone", "Aluminum", "ZA-8"],
    certifications: ["ISO 9001"],
    leadTimeMinDays: 22,
    leadTimeMaxDays: 45,
    pricingMultiplier: "0.80",
    setupFee: "1500.00",
    rating: "4.20",
    capacityLevel: "medium",
  },
  {
    slug: "northwind-cardboard",
    name: "Northwind Packaging",
    tagline: "Custom carton, foam, and unboxing experiences.",
    description:
      "Sustainability-focused packaging house. Recycled kraft, mushroom foam, soy-based inks, and a 5-day proofing cycle.",
    location: "Copenhagen, Denmark",
    country: "Denmark",
    capabilities: [
      "Die cutting",
      "Carton printing",
      "Foam insert",
      "Hand assembly",
    ],
    materials: ["Kraft Cardstock", "Recycled Cardboard", "Mushroom Foam"],
    certifications: ["FSC", "EU Ecolabel"],
    leadTimeMinDays: 7,
    leadTimeMaxDays: 14,
    pricingMultiplier: "0.70",
    setupFee: "180.00",
    rating: "4.60",
    capacityLevel: "high",
  },
  {
    slug: "magnet-house",
    name: "Magnet House Components",
    tagline: "Neodymium and ferrite magnet supply, magnetized to spec.",
    description:
      "Sourcing and finishing house for neodymium magnets — coatings, polarity jigs, and assemblies. Common pairing with CNC + injection molding suppliers.",
    location: "Ningbo, China",
    country: "China",
    capabilities: ["Magnet assembly", "Magnet press-fitting", "Coating"],
    materials: ["Neodymium Magnets", "Neodymium N52", "Ferrite", "SmCo"],
    certifications: ["ISO 9001", "RoHS"],
    leadTimeMinDays: 10,
    leadTimeMaxDays: 24,
    pricingMultiplier: "0.85",
    setupFee: "220.00",
    rating: "4.45",
    capacityLevel: "high",
  },
];

export async function seedSuppliersIfEmpty(): Promise<void> {
  try {
    const [{ c }] = await db
      .select({ c: sql<number>`count(*)::int` })
      .from(suppliersTable);
    if (c > 0) return;
    await db.insert(suppliersTable).values(SUPPLIERS);
    logger.info({ count: SUPPLIERS.length }, "Seeded suppliers");
  } catch (err) {
    logger.error({ err }, "Failed to seed suppliers");
  }
}
