-- Initial baseline migration. Generated by drizzle-kit, then hand-edited to
-- be idempotent so it can baseline an existing database that was previously
-- bootstrapped with `drizzle-kit push`. Every statement is guarded with
-- IF NOT EXISTS or a DO-block existence check; subsequent migrations should
-- be left as drizzle-kit emits them.

CREATE TABLE IF NOT EXISTS "design_messages" (
"id" serial PRIMARY KEY NOT NULL,
"session_id" integer NOT NULL,
"role" text NOT NULL,
"content" text NOT NULL,
"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "design_outputs" (
"id" serial PRIMARY KEY NOT NULL,
"session_id" integer NOT NULL,
"product_name" text NOT NULL,
"category" text NOT NULL,
"summary" text NOT NULL,
"primary_material" text NOT NULL,
"materials" text[] NOT NULL,
"dimensions" text NOT NULL,
"weight_grams" numeric(10, 2),
"processes" text[] NOT NULL,
"bom" jsonb NOT NULL,
"cost_estimate" jsonb NOT NULL,
"image_url" text,
"manufacturing_notes" text NOT NULL,
"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "design_sessions" (
"id" serial PRIMARY KEY NOT NULL,
"user_id" text DEFAULT 'system-seed' NOT NULL,
"title" text NOT NULL,
"status" text DEFAULT 'generating' NOT NULL,
"created_at" timestamp with time zone DEFAULT now() NOT NULL,
"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "design_sessions" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp with time zone;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "orders" (
"id" serial PRIMARY KEY NOT NULL,
"user_id" text DEFAULT 'system-seed' NOT NULL,
"marketplace_listing_id" integer,
"quote_id" integer NOT NULL,
"session_id" integer NOT NULL,
"supplier_id" integer NOT NULL,
"quantity" integer DEFAULT 1 NOT NULL,
"total_cost" numeric(12, 2) NOT NULL,
"designer_user_id" text,
"payout_amount" numeric(12, 2) DEFAULT '0' NOT NULL,
"lead_time_days" integer NOT NULL,
"shipping_address" jsonb NOT NULL,
"status" text DEFAULT 'queued' NOT NULL,
"status_history" jsonb DEFAULT '[]'::jsonb NOT NULL,
"created_at" timestamp with time zone DEFAULT now() NOT NULL,
"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
"deleted_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp with time zone;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quotes" (
"id" serial PRIMARY KEY NOT NULL,
"session_id" integer NOT NULL,
"supplier_id" integer NOT NULL,
"unit_cost" numeric(12, 2) NOT NULL,
"setup_fee" numeric(12, 2) NOT NULL,
"total_cost" numeric(12, 2) NOT NULL,
"lead_time_days" integer NOT NULL,
"process_breakdown" jsonb NOT NULL,
"score_factors" jsonb NOT NULL,
"rank" integer NOT NULL,
"notes" text NOT NULL,
"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "suppliers" (
"id" serial PRIMARY KEY NOT NULL,
"slug" text NOT NULL,
"name" text NOT NULL,
"tagline" text NOT NULL,
"description" text NOT NULL,
"location" text NOT NULL,
"country" text NOT NULL,
"capabilities" text[] NOT NULL,
"materials" text[] NOT NULL,
"certifications" text[] NOT NULL,
"lead_time_min_days" integer NOT NULL,
"lead_time_max_days" integer NOT NULL,
"pricing_multiplier" numeric(4, 2) NOT NULL,
"setup_fee" numeric(10, 2) NOT NULL,
"rating" numeric(3, 2) NOT NULL,
"capacity_level" text NOT NULL,
"created_at" timestamp with time zone DEFAULT now() NOT NULL,
CONSTRAINT "suppliers_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "marketplace_listings" (
"id" serial PRIMARY KEY NOT NULL,
"session_id" integer NOT NULL,
"user_id" text NOT NULL,
"creator_handle" text NOT NULL,
"title" text NOT NULL,
"category" text NOT NULL,
"description" text NOT NULL,
"listing_price" numeric(12, 2) NOT NULL,
"status" text DEFAULT 'active' NOT NULL,
"created_at" timestamp with time zone DEFAULT now() NOT NULL,
"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
"deleted_at" timestamp with time zone,
CONSTRAINT "marketplace_listings_session_id_unique" UNIQUE("session_id")
);
--> statement-breakpoint
ALTER TABLE "marketplace_listings" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp with time zone;--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_profiles" (
"user_id" text PRIMARY KEY NOT NULL,
"display_name" text,
"bio" text,
"avatar_url" text,
"created_at" timestamp with time zone DEFAULT now() NOT NULL,
"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "audit_log" (
"id" bigserial PRIMARY KEY NOT NULL,
"actor_user_id" text,
"action" text NOT NULL,
"target_type" text NOT NULL,
"target_id" text NOT NULL,
"before" jsonb,
"after" jsonb,
"request_id" text,
"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'design_messages_session_id_design_sessions_id_fk') THEN
    ALTER TABLE "design_messages" ADD CONSTRAINT "design_messages_session_id_design_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."design_sessions"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'design_outputs_session_id_design_sessions_id_fk') THEN
    ALTER TABLE "design_outputs" ADD CONSTRAINT "design_outputs_session_id_design_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."design_sessions"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_quote_id_quotes_id_fk') THEN
    ALTER TABLE "orders" ADD CONSTRAINT "orders_quote_id_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."quotes"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_session_id_design_sessions_id_fk') THEN
    ALTER TABLE "orders" ADD CONSTRAINT "orders_session_id_design_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."design_sessions"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'orders_supplier_id_suppliers_id_fk') THEN
    ALTER TABLE "orders" ADD CONSTRAINT "orders_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE restrict ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'quotes_session_id_design_sessions_id_fk') THEN
    ALTER TABLE "quotes" ADD CONSTRAINT "quotes_session_id_design_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."design_sessions"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'quotes_supplier_id_suppliers_id_fk') THEN
    ALTER TABLE "quotes" ADD CONSTRAINT "quotes_supplier_id_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'marketplace_listings_session_id_design_sessions_id_fk') THEN
    ALTER TABLE "marketplace_listings" ADD CONSTRAINT "marketplace_listings_session_id_design_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."design_sessions"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "design_messages_session_id_idx" ON "design_messages" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "design_outputs_session_id_idx" ON "design_outputs" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "design_sessions_user_id_idx" ON "design_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "design_sessions_updated_at_idx" ON "design_sessions" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "design_sessions_deleted_at_idx" ON "design_sessions" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_user_id_idx" ON "orders" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_designer_user_id_idx" ON "orders" USING btree ("designer_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_marketplace_listing_id_idx" ON "orders" USING btree ("marketplace_listing_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_session_id_idx" ON "orders" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_supplier_id_idx" ON "orders" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_status_idx" ON "orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_deleted_at_idx" ON "orders" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_created_at_idx" ON "orders" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quotes_session_id_idx" ON "quotes" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quotes_supplier_id_idx" ON "quotes" USING btree ("supplier_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "marketplace_listings_user_id_idx" ON "marketplace_listings" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "marketplace_listings_status_idx" ON "marketplace_listings" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "marketplace_listings_category_idx" ON "marketplace_listings" USING btree ("category");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "marketplace_listings_deleted_at_idx" ON "marketplace_listings" USING btree ("deleted_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "marketplace_listings_created_at_idx" ON "marketplace_listings" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_target_idx" ON "audit_log" USING btree ("target_type","target_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_actor_idx" ON "audit_log" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_created_at_idx" ON "audit_log" USING btree ("created_at");
