import PDFDocument from "pdfkit";
import { createWriteStream, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const OUT_PATH =
  "artifacts/reality-compiler/public/legal/reality-compiler-dpa.pdf";

mkdirSync(dirname(OUT_PATH), { recursive: true });

const doc = new PDFDocument({
  size: "LETTER",
  margins: { top: 64, left: 64, right: 64, bottom: 64 },
  info: {
    Title: "Reality Compiler — Data Processing Addendum",
    Author: "Reality Compiler",
    Subject: "Data Processing Addendum (GDPR / UK GDPR / CCPA)",
    Keywords: "DPA, GDPR, CCPA, Reality Compiler",
  },
});

doc.pipe(createWriteStream(OUT_PATH));

doc
  .font("Helvetica-Bold")
  .fontSize(20)
  .text("Reality Compiler", { continued: false })
  .fontSize(14)
  .text("Data Processing Addendum");

doc
  .moveDown(0.5)
  .font("Helvetica")
  .fontSize(10)
  .fillColor("#555")
  .text("Last updated: May 3, 2026")
  .fillColor("#000");

doc.moveDown();

const sections = [
  {
    h: "1. Scope and roles",
    p: 'This Data Processing Addendum ("DPA") supplements the Reality Compiler Terms of Service ("Agreement") between Reality Compiler ("Processor") and the customer ("Controller"). It applies whenever Reality Compiler processes personal data on behalf of the Controller in the course of providing the Service. The Controller determines the purposes and means of processing; Reality Compiler acts solely as Processor and processes personal data only on documented instructions from the Controller.',
  },
  {
    h: "2. Subject matter, duration, nature and purpose",
    p: "The subject matter of processing is the personal data submitted to or generated by the Service, including account profile fields, prompts that may contain personal data, shipping addresses, and order history. Processing lasts for the duration of the Agreement and any subsequent retention period required by law. The nature and purpose of processing is to operate the Service: generating designs, fulfilling marketplace orders, routing payouts, providing support, and meeting tax/audit obligations.",
  },
  {
    h: "3. Categories of data subjects and personal data",
    p: "Data subjects include the Controller's authorised users, marketplace buyers, and any third parties whose data the Controller chooses to submit. Personal data categories include: identifiers (Clerk user id, email), profile data (display name, bio, avatar), shipping data (recipient, address, postal code, country), commercial data (order line items, prices, payout amounts), and content submitted via prompts.",
  },
  {
    h: "4. Sub-processors",
    p: "Reality Compiler engages the following sub-processors: Clerk Inc. (authentication), Neon Inc. (managed Postgres), Google Cloud (object storage), OpenAI / Anthropic (AI inference), and the contract manufacturer the Controller selects for fulfilment. Reality Compiler will give the Controller at least 30 days' prior notice of any new sub-processor and provide a reasonable means to object.",
  },
  {
    h: "5. Security measures",
    p: "Reality Compiler implements technical and organisational measures appropriate to the risk, including: encryption in transit (TLS 1.2+) and at rest, principle-of-least-privilege access control, audit logging of sensitive actions, vulnerability management, and access review on personnel changes. Production secrets are stored in Replit Secrets and never committed to source control.",
  },
  {
    h: "6. Data subject rights",
    p: "The Service exposes self-serve endpoints to support data subject rights: GET /api/me/export returns a complete JSON archive of the requesting user's data, and DELETE /api/me triggers a soft-delete with a 30-day grace window followed by hard purge of all stored objects. Reality Compiler will also assist the Controller, taking into account the nature of processing, to fulfil rights requests received from data subjects directly.",
  },
  {
    h: "7. Personal data breach notification",
    p: "Reality Compiler will notify the Controller without undue delay, and in any event within 72 hours, of becoming aware of a personal data breach affecting the Controller's data, providing the information reasonably necessary for the Controller to meet its own notification obligations under Article 33 GDPR (or analogous laws).",
  },
  {
    h: "8. International transfers",
    p: "Where personal data is transferred outside the EEA, UK, or Switzerland to a country without an adequacy decision, the parties rely on the EU Standard Contractual Clauses (Module Two: Controller-to-Processor) which are incorporated into this DPA by reference, together with the UK Addendum where applicable.",
  },
  {
    h: "9. Audits",
    p: "Reality Compiler will make available to the Controller, upon written request and subject to a reasonable confidentiality undertaking, the information necessary to demonstrate compliance with this DPA. The Controller may exercise audit rights through written questionnaires once per year; on-site audits are available where required by supervisory authorities.",
  },
  {
    h: "10. Return or deletion at end of services",
    p: "On termination of the Agreement, the Controller may export its data via the self-serve endpoints described in Section 6 within 30 days. After that period Reality Compiler will delete all personal data unless retention is required by law (e.g., financial records). Sub-processors are obligated to do the same.",
  },
  {
    h: "11. Order of precedence",
    p: "In the event of a conflict between this DPA and the Agreement, this DPA prevails with respect to data protection matters.",
  },
];

doc.font("Helvetica").fontSize(11);
for (const s of sections) {
  doc.moveDown(0.6).font("Helvetica-Bold").fontSize(12).text(s.h);
  doc.moveDown(0.2).font("Helvetica").fontSize(10).text(s.p, {
    align: "justify",
    lineGap: 2,
  });
}

doc
  .moveDown(1.5)
  .fontSize(9)
  .fillColor("#666")
  .text(
    "This DPA is provided as a starting template. Customers with specific regulatory requirements (HIPAA, PCI-DSS, sector-specific obligations) should contact privacy@reality-compiler.example to negotiate bespoke terms.",
    { align: "center" },
  );

doc.end();

console.log(`Wrote ${OUT_PATH}`);
